[package]
name = "wat-defs"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
convert_case = "0.8.0"
derive-quote-to-tokens = "0.1.1"
proc-macro2 = "1.0.101"
quote = "1.0.41"
syn = "2.0.106"
